### ISSUE TITLE
Doesn't work on Windows95

### ISSUE THREAD

**Issue by paulogdm** [brentvatne/do-not-star-this-or-you-will-be-fired#2]
Can we have some data on compatibility?

I also tried on my Palm.

**Comment by brentvatne** [comment]
works for me on windows 3.1 so that's weird, can you send me your computer and palm so i can test

**Comment by paulogdm** [comment]
@brentvatne it worked after `rm -rf node_modules` in production. Closing the issue so I can look for my the next gig.
